name: Create Action

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PNPM
        uses: pnpm/setup@v2.1.0
        with:
          runtime: node@v24
          require-lockfile: true

      - name: Build
        run: |
          rm -rf ./dist
          pnpm run prepare
          cp ./package.json ./dist/
          pnpm install --prod --no-lockfile --prefix ./dist

      - name: Commit Build Artifacts
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "Build distribution files" || echo "No changes to commit"
          git push
